"""Type stubs for the gtars.vrs module."""

from typing import Any, Dict


def vrs_digest(seq_digest: str, start: int, end: int, alt: str) -> str: ...
def vrs_id(seq_digest: str, start: int, end: int, alt: str) -> str: ...
def normalize_allele(
    sequence: str, start: int, ref_allele: str, alt_allele: str
) -> Dict[str, Any]: ...
def location_digest(seq_digest: str, start: int, end: int) -> str: ...
