[package]
name = "refget"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.135"
seq_io = "0.3.2"
sha2 = "0.10.7"
md-5 = "0.10.5"
base64-url = "2.0.0"
memmap2 = "0.5"  # For memory-mapped file I/O
chrono = { version = "0.4", features = ["serde"] }  # For timestamps
anyhow = { workspace = true }
serde = { workspace = true }
flate2 = { workspace = true }

# our code
gtars-core = { path = "../gtars-core" }

[dev-dependencies]
tempfile = "3.8.1"