[package]
name = "refget"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.203", features=["derive"] }
serde_json = "1.0.135"
seq_io = "0.3.2"
sha2 = "0.10.7"
md-5 = "0.10.5"
base64-url = "2.0.0"
anyhow = "1.0.82"
flate2 = "1.0.28"
memmap2 = "0.5"  # For memory-mapped file I/O
chrono = { version = "0.4", features = ["serde"] }  # For timestamps

# our code
gtars-core = { path = "../gtars-core" }

[dev-dependencies]
tempfile = "3.8.1"