[package]
name = "tokenizers"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
hf-hub = { version = "0.4.3", optional = true}
toml = "0.8.14"

# share workspace dependencies
anyhow = { workspace = true }
fxhash = { workspace = true }
serde = { workspace = true }

# our code
gtars-core = { path = "../gtars-core" }
overlaprs = { path = "../overlaprs" }

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"

[features]
default = []
huggingface = ["dep:hf-hub"]