"""Type stubs for the gtars.reftx module.

The real implementation lives in `gtars-python/src/reftx/mod.rs`.
"""

from enum import Enum
from typing import Any, Dict, List, Optional


class Strand(Enum):
    Plus: int
    Minus: int

    @classmethod
    def from_str(cls, s: str) -> "Strand": ...


class ManeStatus:
    select: bool
    plus_clinical: bool

    def __init__(self, select: bool = False, plus_clinical: bool = False) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...


class Exon:
    start: int
    end: int
    cds_start: Optional[int]
    cds_end: Optional[int]

    def __init__(
        self,
        start: int,
        end: int,
        cds_start: Optional[int] = None,
        cds_end: Optional[int] = None,
    ) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...


class Transcript:
    accession: str
    gene: Optional[str]
    chrom: str
    strand: Strand
    cds_start: Optional[int]
    cds_end: Optional[int]
    exons: List[Exon]
    mane: Optional[ManeStatus]

    def to_dict(self) -> Dict[str, Any]: ...


class TxStoreBuilder:
    def __init__(self) -> None: ...
    def add_transcript(self, value: Any) -> None: ...
    def add_chrom_mapping(self, name: str, accession: str) -> None: ...
    def load_cdot(self, path: str) -> int: ...
    def load_cdot_gz(self, path: str) -> int: ...
    def load_mane_summary(self, path: str) -> int: ...
    def __len__(self) -> int: ...
    def build(self, out_path: str) -> None: ...


class ReadonlyTxStore:
    @classmethod
    def open(cls, path: str) -> "ReadonlyTxStore": ...
    def lookup(self, accession: str) -> Optional[Transcript]: ...
    def lookup_mane(self, gene: str) -> Optional[Transcript]: ...
    def has_mane_index(self) -> bool: ...
    def get_chrom_accession(self, accession: str) -> Optional[str]: ...
    def get_strand(self, accession: str) -> Optional[Strand]: ...
    def __len__(self) -> int: ...


class CoordinateMapper:
    def __init__(self, store: ReadonlyTxStore) -> None: ...
    def c_to_g(self, accession: str, c_pos: int, datum: Optional[int] = None) -> int: ...
    def n_to_g(self, accession: str, n_pos: int) -> int: ...
    def c_to_g_full(
        self, accession: str, c_pos: int, datum: Optional[int] = None
    ) -> Dict[str, Any]: ...
    def n_to_g_full(self, accession: str, n_pos: int) -> Dict[str, Any]: ...
    def c_to_g_by_gene(
        self, gene: str, c_pos: int, datum: Optional[int] = None
    ) -> Dict[str, Any]: ...


class ReftxProvider:
    def __init__(self, store: ReadonlyTxStore) -> None: ...


class MappingError(Exception): ...
class TxStoreError(Exception): ...
