[package]
name = "igd"
version = "0.5.0"
edition = "2024"

[dependencies]
# our code
gtars-core = { path = "../gtars-core" }

# shared workspace dependencies
anyhow = { workspace = true }
byteorder = { workspace = true }