[build-system]
requires = ["maturin>=1.3,<2.0"]
build-backend = "maturin"

[project]
name = "gtars"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "maturin>=1.8.1",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "py_src"
module-name = "gtars.gtars"

[tool.setuptools.dynamic]
readme = {file = "README.md", content-type = "text/markdown"}


