[package]
name = 'gtars-r'
version = '0.2.5'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'gtars'

[dependencies]
extendr-api = '*'
openssl = { version = "0.10", features = ["vendored"] }
# gtars = { git = "https://github.com/databio/gtars", branch = "r_tokenizers" }
gtars = { path = "../../../../gtars" }
