[package]
name = 'gtars-r'
version = '0.1.2'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'gtars'

[dependencies]
extendr-api = '*'
gtars = { git = "https://github.com/databio/gtars", branch = "dev" }
# gtars = { path = "../../../../gtars" }
