[package]
name = "vocab"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
gtokenizers = "0.0.18"
indicatif = "0.17.7"

[dev-dependencies]
rstest = "0.18.2"