[package]
name = "vocab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtokenizers = "0.0.17"
indicatif = "0.17.7"