[package]
name = "overlaprs"
version = "0.5.0"
edition = "2024"

[dependencies]
# our code
gtars-core = { path = "../gtars-core" }
num-traits = "0.2.19"

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"