[package]
name = "genimtools-py"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "genimtools"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
genimtools = { path = "../" }
