[package]
name = "genimtools-py"
version = "0.0.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "genimtools"
crate-type = ["cdylib"]

[dependencies]
genimtools = { path = "../genimtools" }
pyo3 = "0.20.0"
