[package]
name = "gtars-r"
version = "0.5.0"
edition = "2024"  # Match workspace edition

[lib]
name = "gtars"
crate-type = ["cdylib"]

[dependencies]
extendr-api = "0.8"
anyhow = { workspace = true }

### use these when developing with rextendr::clean() and rextender::document()
# gtars-core = { path = "../../../gtars-core" }
# io = { path = "../../../io" }
# igd = { path = "../../../igd" }
# refget = { path = "../../../refget" }
# tokenizers = { path = "../../../tokenizers", features = ["huggingface"] }

### use these to build the r package with R CMD build AFTER pushing changes to appropriate github branch
gtars-core = { git = "https://github.com/databio/gtars", branch = "r-workspace" }
io = { git = "https://github.com/databio/gtars", branch = "r-workspace" }
igd = { git = "https://github.com/databio/gtars", branch = "r-workspace" }
refget = { git = "https://github.com/databio/gtars", branch = "r-workspace" }
tokenizers = { git = "https://github.com/databio/gtars", branch = "r-workspace", features = ["huggingface"] }
