# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gtars_wrappers", use_symbols = TRUE, package_name = "gtars")

#' @usage NULL
#' @useDynLib gtars, .registration = TRUE
NULL

#' Write tokens to a gtok file
#' @export
#' @param filename A string representing the path to the gtok file.
read_tokens_from_gtok <- function(filename) .Call(wrap__r_read_tokens_from_gtok, filename)

#' Write tokens to a gtok file
#' @export
#' @param filename A string representing the path to the gtok file.
write_tokens_to_gtok <- function(filename, tokens) invisible(.Call(wrap__r_write_tokens_to_gtok, filename, tokens))


# nolint end
