# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gtars_wrappers", use_symbols = TRUE, package_name = "gtars")

#' @usage NULL
#' @useDynLib gtars, .registration = TRUE
NULL

`__init__` <- function() invisible(.Call(wrap____init__))

#' @export
igd_search <- function(database_path, query_path) .Call(wrap__igd_search, database_path, query_path)


# nolint end
