name: Run tests

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4'
    
    - name: Set R library path
      run: echo "LD_LIBRARY_PATH=$(R RHOME)/lib" >> "$GITHUB_ENV"

    - name: Run tests
      run: cargo test --verbose --workspace --all-features

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Build and install Python bindings
      working-directory: ./gtars-python
      run: |
        uv venv
        uv pip install maturin pytest
        uv run maturin develop --release
    - name: Run Python tests
      working-directory: ./gtars-python
      run: uv run pytest tests/ -v